hello: |
  <b>–ü—Ä–∏–≤–µ—Ç, {first_name}! ‚ù§Ô∏è</b>
  
  –ó–¥–µ—Å—å —Ç—ã –º–æ–∂–µ—à—å –ø—Ä–∏–æ–±—Ä–µ—Å—Ç–∏ –∫—É—Ä—Å <b>¬´–ü—Ä–æ –±–µ—Ä–µ–º–µ–Ω–Ω–æ—Å—Ç—å¬ª</b>, –≤ –∫–æ—Ç–æ—Ä—ã–π —è –≤–ª–æ–∂–∏–ª–∞ –≤—Å–µ —Å–≤–æ–∏ –∑–Ω–∞–Ω–∏—è, —Å–≤–æ–π 25 –ª–µ—Ç–Ω–∏–π –æ–ø—ã—Ç, —Å–≤–æ—é –ª—é–±–æ–≤—å, –¥–ª—è —Ç–æ–≥–æ, —á—Ç–æ–±—ã —Ç—ã —Å—Ç–∞–ª–∞ –ú–ê–ú–û–ô –∑–¥–æ—Ä–æ–≤–æ–≥–æ –º–∞–ª—ã—à–∞!ü§±üèº

  –¢—ã –º–æ–∂–µ—à—å –ø—Ä–∏–æ–±—Ä–µ—Å—Ç–∏ –≤–µ—Å—å –∫—É—Ä—Å, –≤ –∫–æ—Ç–æ—Ä–æ–º –±—É–¥—É—Ç –≤—Å–µ —Ä–∞–∑–¥–µ–ª—ã:
  <i>- –ø–æ–¥–≥–æ—Ç–æ–≤–∫–∞ –∏ –ø–ª–∞–Ω–∏—Ä–æ–≤–∞–Ω–∏–µ –±–µ—Ä–µ–º–µ–Ω–Ω–æ—Å—Ç–∏
  - 1 —Ç—Ä–∏–º–µ—Å—Ç—Ä
  - 2 —Ç—Ä–∏–º–µ—Å—Ç—Ä
  - 3 —Ç—Ä–∏–º–µ—Å—Ç—Ä</i>

  –ò–ª–∏ –ø—Ä–∏–æ–±—Ä–µ—Å—Ç–∏ –∫–∞–∂–¥—ã–π —Ä–∞–∑–¥–µ–ª –ø–æ –æ—Ç–¥–µ–ª—å–Ω–æ—Å—Ç–∏.

  –¢–∞–∫ –∂–µ —É –º–µ–Ω—è –µ—Å—Ç—å –∫—É—Ä—Å
  <b>¬´–ù–µ—Ä–∞–∑–≤–∏–≤–∞—é—â–∞—è—Å—è –±–µ—Ä–µ–º–µ–Ω–Ω–æ—Å—Ç—å¬ª</b>

  –û–Ω –ø–æ–º–æ–∂–µ—Ç –ø—Ä–µ–æ–¥–æ–ª–µ—Ç—å —ç—Ç–æ—Ç –ø–µ—Ä–∏–æ–¥ –∏ —Ä–æ–¥–∏—Ç—å —Å–≤–æ—é –¥–æ–ª–≥–æ–∂–¥–∞–Ω–Ω—É—é –ª—è–ª–µ—á–∫—É‚ù§Ô∏è

  –ü–æ—Å–ª–µ –ø—Ä–æ—Ö–æ–∂–¥–µ–Ω–∏—è –∫—É—Ä—Å–∞ —É –Ω–∞—Å –±—É–¥–µ—Ç –ø—Ä—è–º–æ–π —ç—Ñ–∏—Ä , –≥–¥–µ —Ç—ã –ø–æ–ª—É—á–∏—à—å –æ—Ç–≤–µ—Ç—ã –Ω–∞ —Å–≤–æ–∏ –≤–æ–ø—Ä–æ—Å—ã ‚úÖ 

  –°–∫–æ—Ä–µ–µ –ø—Ä–∏—Å–æ–µ–¥–∏–Ω—è–π—Å—è ‚ù§Ô∏è

choose_chapter: "–í—ã–±–µ—Ä–∏—Ç–µ —Ä–∞–∑–¥–µ–ª"
buy_chapter_info: |
  <b>{name}
  
  –°–æ–¥–µ—Ä–∂–∞–Ω–∏–µ —Ä–∞–∑–¥–µ–ª–∞:</b>
  <blockquote>{description}</blockquote>
  <b>–°—Ç–æ–∏–º–æ—Å—Ç—å:</b> {price} ‚ÇΩ
confirm_purchase_header: |
  <b>–ü–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏–µ</b>

  –í–∞—à —ç–ª. –∞–¥—Ä–µ—Å: {email}
  
  –í—ã –ø–æ–∫—É–ø–∞–µ—Ç–µ —Ä–∞–∑–¥–µ–ª(-—ã) –∫—É—Ä—Å–∞:

confirm_purchase_course_line: |
  ‚Ä¢ {name} ‚Äî <b>{price} ‚ÇΩ</b>

confirm_purchase_footer: |
  üí∞ <b>–û–±—â–∞—è —Å—É–º–º–∞ –∫ –æ–ø–ª–∞—Ç–µ: {total} ‚ÇΩ</b>
support: |
  <b>üí¨ –ù—É–∂–Ω–∞ –ø–æ–º–æ—â—å?</b>
  
  –ü–æ–∂–∞–ª—É–π—Å—Ç–∞, –æ–±—Ä–∞—Ç–∏—Ç–µ—Å—å –≤ –Ω–∞—à—É —Å–ª—É–∂–±—É –ø–æ–¥–¥–µ—Ä–∂–∫–∏:
  <b>@mozhaevaliya</b>