buy_courses: "Приобрести курс"
chapter: "Раздел {num_of_chapter}"
go_to_pay: "Перейти к оплате"
go_to_channel: "Перейти в канал"
go_back: "Назад"

main_menu:
  all_courses: "Все разделы"
  my_courses: "Мои оплаченные разделы/доступы"
  documents: "Правила и документы"
  support: "Служба поддержки"
