hello: |
  <b>Привет, {first_name}! ❤️</b>
  Этот бот поможет тебе попасть в закрытый телеграмм канал, где ты узнаешь больше о беременности и родах.
  
  Ты можешь приобрести весь курс, в котором будет вся информация, а так же бонусные уроки и прямой эфир лично со мной .

  Либо приобрести отдельные разделы по твоему желанию.

  Скорее присоединяйся ❤️

choose_chapter: "Выберите раздел"
buy_chapter_info: |
  <b>Описание:</b>
  {description}

  <b>Стоимость:</b> {price} ₽
confirm_purchase: |
  <b>Подтверждение</b>

  Ваш эл. адрес: {email}

  Вы покупаете раздел курса <b>{name}</b>
  <b>Сумма к оплате:</b> {price} ₽