mail1310: |
  –ü—Ä–∏–≤–µ—Ç, –ø—Ä–æ–¥–∞–∂–∞ –º–æ–µ–≥–æ –ê–≤—Ç–æ—Ä—Å–∫–æ–≥–æ –∫—É—Ä—Å–∞ ¬´–ü—Ä–æ –±–µ—Ä–µ–º–µ–Ω–Ω–æ—Å—Ç—å¬ª –û–¢–ö–†–´–¢–ê‚úÖ 

  –í –Ω–µ–º —è —Ä–∞—Å—Å–∫–∞–∑–∞–ª–∞ –∫–∞–∫ –ó–∞—á–∞—Ç—å, –í—ã–Ω–æ—Å–∏—Ç—å –∏ –†–æ–¥–∏—Ç—å –ó–¥–æ—Ä–æ–≤—É—é –∏ –£–º–Ω–µ–Ω—å–∫—É—é –õ—è–ª–µ—á–∫—É‚ù§Ô∏è

  –ë–æ–ª–µ–µ 10 —á–∞—Å–æ–≤ –¥–æ–∫–∞–∑–∞—Ç–µ–ª—å–Ω–æ–π –º–µ–¥–∏—Ü–∏–Ω—ã –ø–æ —Å–∞–º—ã–º –ø–æ—Å–ª–µ–¥–Ω–∏–º –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏—è–º –≤ –æ–±–ª–∞—Å—Ç–∏ –∑–∞—á–∞—Ç–∏—è –∏ –±–µ—Ä–µ–º–µ–Ω–Ω–æ—Å—Ç–∏üíï
mail1510_1: "–î–µ–≤–æ—á–∫–∏, –¥–æ –∑–∞–∫—Ä—ã—Ç–∏—è –ø—Ä–æ–¥–∞–∂ –∫—É—Ä—Å–∞ ¬´–ü—Ä–æ –±–µ—Ä–µ–º–µ–Ω–Ω–æ—Å—Ç—å¬ª –æ—Å—Ç–∞–ª–æ—Å—å 3 –¥–Ω—è, –ø–æ—Ç–æ—Ä–æ–ø–∏—Å—å."
mail1510: |
  –ß—Ç–æ –≤–Ω—É—Ç—Ä–∏?
  
  –ö—É—Ä—Å <i>¬´–í–°–Å –ü–†–û –ë–ï–†–ï–ú–ï–ù–ù–û–°–¢–¨¬ª</i>
  <blockquote><b>–ü–û–î–ì–û–¢–û–í–ö–ê –∏ –ü–õ–ê–ù–ò–†–û–í–ê–ù–ò–ï</b>
  ‚ÅÉ –û–±—Ä–∞–∑ –∂–∏–∑–Ω–∏ –ø—Ä–∏ –ø–ª–∞–Ω–∏—Ä–æ–≤–∞–Ω–∏–∏
  ‚ÅÉ –ê–Ω–∞–ª–∏–∑—ã –ø—Ä–∏ –ø–æ–¥–≥–æ—Ç–æ–≤–∫–µ –∏ –ø–ª–∞–Ω–∏—Ä–æ–≤–∞–Ω–∏–∏;
  ‚ÅÉ –í–∏—Ç–∞–º–∏–Ω—ã –ø—Ä–∏ –ø–ª–∞–Ω–∏—Ä–æ–≤–∞–Ω–∏–∏ 
  ‚ÅÉ –ó–∞—á–∞—Ç–∏–µ;
  - –°–∫–æ–ª—å–∫–æ –Ω—É–∂–Ω–æ –≤—Ä–µ–º–µ–Ω–∏ —á—Ç–æ–±—ã –∑–∞–±–µ—Ä–µ–º–µ–Ω–µ—Ç—å
  - –≠–º–æ—Ü–∏–æ–Ω–∞–ª—å–Ω—ã–π —Ñ–∞–∫—Ç–æ—Ä 
  - –ë–µ—Ä–µ–º–µ–Ω–Ω–æ—Å—Ç—å –ø–æ —Ç–µ–ª–µ—Ñ–æ–Ω—É 
  - –°–∫–æ–ª—å–∫–æ –Ω—É–∂–Ω–æ –ø–æ–ª–æ–≤—ã—Ö –∞–∫—Ç–æ–≤ 
  - –†–∞—Å—á–µ—Ç –æ–≤—É–ª—è—Ü–∏–∏ 
  - –õ—É—á—à–∏–µ –ø–æ–∑—ã –¥–ª—è –±–µ—Ä–µ–º–µ–Ω–Ω–æ—Å—Ç–∏ 
  - –°–∏–º–ø—Ç–æ–º—ã –æ–≤—É–ª—è—Ü–∏–∏ 
  - –õ–∞–π—Ñ—Ö–∞–∫ —á—Ç–æ–±—ã –ø–æ–ª—É—á–∏–ª—Å—è –º–∞–ª—å—á–∏–∫/–¥–µ–≤–æ—á–∫–∞ 
  - –í—Ä–µ–¥–Ω—ã–µ –ø—Ä–∏–≤—ã—á–∫–∏ –ø—Ä–∏ –∑–∞—á–∞—Ç–∏–∏ 
  - –ö–æ—Å–º–µ—Ç–æ–ª–æ–≥–∏—á–µ—Å–∫–∏–µ –ø—Ä–æ—Ü–µ–¥—É—Ä—ã
  
  <b>–ü–ï–†–í–´–ô –¢–†–ò–ú–ï–°–¢–†</b>
  ‚ÅÉ –ù–∞—á–∞–ª–æ –±–µ—Ä–µ–º–µ–Ω–Ω–æ—Å—Ç–∏;
  ‚ÅÉ –ë–∏–æ—Ö–∏–º–∏—á–µ—Å–∫–∞—è –±–µ—Ä–µ–º–µ–Ω–Ω–æ—Å—Ç—å;
  ‚ÅÉ –ü—Ä–∏–∑–Ω–∞–∫–∏ –±–µ—Ä–µ–º–µ–Ω–Ω–æ—Å—Ç–∏;
  ‚ÅÉ –ê–Ω–∞–ª–∏–∑—ã –ø—Ä–∏ –ø–æ—Å—Ç–∞–Ω–æ–≤–∫–µ –Ω–∞ —É—á–µ—Ç;
  ‚ÅÉ –û–±—Ä–∞–∑ –∂–∏–∑–Ω–∏ ;
  ‚ÅÉ –í–∏—Ç–∞–º–∏–Ω—ã;
  ‚ÅÉ –ü–µ—Ä–≤—ã–π —Å–∫—Ä–∏–Ω–∏–Ω–≥;
  ‚ÅÉ –†–∞–∑–±–æ—Ä 1 —Å–∫—Ä–∏–Ω–∏–Ω–≥–∞(2 –ø—Ä–∏–º–µ—Ä–∞);
  ‚ÅÉ –ù–ò–ü–¢;
  ‚ÅÉ –¢–æ–∫—Å–∏–∫–æ–∑;
  ‚ÅÉ –ö–∞–∫ –º–µ–Ω—è–µ—Ç—Å—è –º–∞—Å—Å–∞ —Ç–µ–ª–∞;
  
  <b>–í–¢–û–†–û–ô –¢–†–ò–ú–ï–°–¢–†</b> 
  ‚ÅÉ –®–µ–≤–µ–ª–µ–Ω–∏—è –ø–ª–æ–¥–∞;
  ‚ÅÉ –í–∏—Ç–∞–º–∏–Ω—ã;
  ‚ÅÉ –†–∞–∑–≤–∏—Ç–∏–µ –ø–ª–æ–¥–∞;
  ‚ÅÉ –í—Ç–æ—Ä–æ–π —Å–∫—Ä–∏–Ω–∏–Ω–≥;
  ‚ÅÉ –ò–∑–º–µ–Ω–µ–Ω–∏—è –≤ –æ—Ä–≥–∞–Ω–∏–∑–º–µ;
  ‚ÅÉ –û–±—Ä–∞–∑ –∂–∏–∑–Ω–∏ –≤–æ –≤—Ç–æ—Ä–æ–º —Ç—Ä–∏–º–µ—Å—Ç—Ä–µ;
  ‚ÅÉ –†–∞—Å—Ç—è–∂–∫–∏ ,–ø–∏–≥–º–µ–Ω—Ç—ã–µ –ø—è—Ç–Ω–∞;
  ‚ÅÉ –ù–∞–±–æ—Ä –≤–µ—Å–∞;
  ‚ÅÉ –í—ã–¥–µ–ª–µ–Ω–∏—è;
  ‚ÅÉ –ê–Ω–∞–ª–∏–∑—ã –≤–æ –≤—Ç–æ—Ä–æ–º —Ç—Ä–∏–º–µ—Å—Ç—Ä–µ;
  ‚ÅÉ –ì–ª—é–∫–æ–∑–æ—Ç–æ–ª–µ—Ä–∞–Ω—Ç–Ω—ã–π —Ç–µ—Å—Ç(–ì–¢–¢);
  ‚ÅÉ –ì–µ—Å—Ç–∞—Ü–∏–æ–Ω–Ω—ã–π —Å–∞—Ö–∞—Ä–Ω—ã–π –¥–∏–∞–±–µ—Ç;
  
  <b>–¢–†–ï–¢–ò–ô –¢–†–ò–ú–ï–°–¢–†</b>
  ‚ÅÉ –¢—Ä–µ—Ç–∏–π —Å–∫—Ä–∏–Ω–∏–Ω–≥;
  ‚ÅÉ –û—Ç—ë–∫–∏ –±–µ—Ä–µ–º–µ–Ω–Ω—ã—Ö;
  ‚ÅÉ –ê–Ω–∞–ª–∏–∑—ã;
  ‚ÅÉ –ü–æ–ª–æ–∂–µ–Ω–∏–µ –ø–ª–æ–¥–∞;
  ‚ÅÉ –í—ã–¥–µ–ª–µ–Ω–∏–µ –≤–æ –≤—Ä–µ–º—è –±–µ—Ä–µ–º–µ–Ω–Ω–æ—Å—Ç–∏ ;
  ‚ÅÉ –ü–æ–¥–≥–æ—Ç–æ–≤–∫–∞ —Ä–æ–¥–æ–≤—ã—Ö –ø—É—Ç–µ–π;
  ‚ÅÉ –í–∞–∫—Ü–∏–Ω–∞—Ü–∏—è –±–µ—Ä–µ–º–µ–Ω–Ω–æ–π;
  ‚ÅÉ –ö–¢–ì –ø–ª–æ–¥–∞;
  ‚ÅÉ –ù–∞–±–æ—Ä –≤–µ—Å–∞;
  ‚ÅÉ –°—Ö–≤–∞—Ç–∫–∏;
  ‚ÅÉ –ü–æ–¥–≥–æ—Ç–æ–≤–∫–∞ –∫ —Ä–æ–¥–∞–º;
  ‚ÅÉ –°–∏–º—É–ª—è—Ü–∏—è —Ä–æ–¥–æ–≤;
  ‚ÅÉ –°–∏–º—Ñ–∏–∑–∏—Ç;
  ‚ÅÉ –ü–µ—Ä–µ–Ω–∞—à–∏–≤–∞–Ω–∏–µ;
  
  <b>–†–û–î–´</b>
  ‚ÅÉ –ü—Ä–µ–¥–≤–µ—Å—Ç–Ω–∏–∫–∏ —Ä–æ–¥–æ–≤;
  ‚ÅÉ –ü–µ—Ä–∏–æ–¥—ã —Ä–æ–¥–æ–≤;
  ‚ÅÉ –û–±–µ–∑–±–æ–ª–∏–≤–∞–Ω–∏–µ —Ä–æ–¥–æ–≤;
  ‚ÅÉ –≠–ø–∏–∑–∏–æ—Ç–æ–º–∏—è;
  ‚ÅÉ –†–æ–¥—ã –ø—Ä–∏–¥—É–º–∞–ª–∞ –ø—Ä–∏—Ä–æ–¥–∞;
  ‚ÅÉ –í–∞–∫—Ü–∏–Ω–∞—Ü–∏—è –Ω–æ–≤–æ—Ä–æ–∂–¥–µ–Ω–Ω—ã—Ö;
  ‚ÅÉ –ì–∏–≥–∏–µ–Ω–∞ –ø–æ—Å–ª–µ —Ä–æ–¥–æ–≤;
  ‚ÅÉ –£—Ö–æ–¥ –∑–∞ –º–æ–ª–æ—á–Ω—ã–º–∏ –∂–µ–ª–µ–∑–∞–º–∏;
  ‚ÅÉ –í–æ—Å—Å—Ç–∞–Ω–æ–≤–ª–µ–Ω–∏–µ –æ—Ä–≥–∞–Ω–∏–∑–º–∞;
  ‚ÅÉ –ü–µ—Ä–≤—ã–µ –≥–æ—Å—Ç–∏;
  ‚ÅÉ –ö–æ—Ä–º–ª–µ–Ω–∏–µ –≥—Ä—É–¥—å—é;
  
  <b>–û–ë–©–ò–ï –¢–ï–ú–´</b>
  ‚ÅÉ –°–æ–≤–º–µ—Å—Ç–∏–º–æ—Å—Ç—å –≤–∏—Ç–∞–º–∏–Ω–æ–≤;
  ‚ÅÉ –ö–æ–≥–¥–∞ —Å—Ç–æ–∏—Ç –∏–¥—Ç–∏ –∫ –≤—Ä–∞—á—É;
  ‚ÅÉ –ö–∞–Ω–¥–∏–¥–æ–∑ (–º–æ–ª–æ—á–Ω–∏—Ü–∞);
  ‚ÅÉ –õ–µ—á–µ–Ω–∏–µ –∑—É–±–æ–≤ ;
  ‚ÅÉ –ü–µ—Ä–µ–ª–µ—Ç—ã /–ø–æ–µ–∑–¥–∫–∏ ;
  ‚ÅÉ –ë–æ–ª—å –≤ —Å—É—Å—Ç–∞–≤–∞—Ö;
  ‚ÅÉ –†–µ–∑—É—Å –∫–æ–Ω—Ñ–ª–∏–∫—Ç;
  ‚ÅÉ –ê–ª–ª–µ—Ä–≥–∏—è ;
  ‚ÅÉ –í–æ–∂–¥–µ–Ω–∏–µ –∞–≤—Ç–æ;
  ‚ÅÉ –†–∏–Ω–∏—Ç –±–µ—Ä–µ–º–µ–Ω–Ω—ã—Ö;
  ‚ÅÉ –ì–æ–ª–æ–≤–Ω—ã–µ –±–æ–ª–∏ ;
  ‚ÅÉ –ü—Ä–µ—ç–∫–ª–∞–º–ø—Å–∏—è;
  ‚ÅÉ –ó–∞–¥–µ—Ä–∂–∫–∞ —Ä–æ—Å—Ç–∞ –ø–ª–æ–¥–∞;
  ‚ÅÉ –û–†–í–ò/ –≥—Ä–∏–ø–ø –≤–æ –≤—Ä–µ–º—è –±–µ—Ä–µ–º–µ–Ω–Ω–æ—Å—Ç–∏; 
  
  +–ë–û–ù–£–°–ù–´–ï –£–†–û–ö–ò 
  - –ú—ã—à—Ü—ã —Ç–∞–∑–æ–≤–æ–≥–æ –¥–Ω–∞ 
  - –¢–µ—Ö–Ω–∏–∫–∞ –¥—ã—Ö–∞–Ω–∏—è –¥–ª—è –±–µ—Ä–µ–º–µ–Ω–Ω—ã—Ö –¥–µ–≤—É—à–µ–∫ 
  - –¢–µ—Ö–Ω–∏–∫–∞ –¥—ã—Ö–∞–Ω–∏—è ¬´–ë–æ–¥–∏—Ñ–ª–µ–∫—Å¬ª</blockquote>

mail1710: |
  –ï—Å–ª–∏ —Ç—ã –∂–¥–∞–ª–∞ –∑–Ω–∞–∫, —Ç–æ —ç—Ç–æ –æ–Ω!

  –î–æ—Å—Ç—É–ø –∫ –∫—É—Ä—Å—É ¬´–ü—Ä–æ –±–µ—Ä–µ–º–µ–Ω–Ω–æ—Å—Ç—å¬ª –∑–∞–∫—Ä–æ–µ—Ç—Å—è —á–µ—Ä–µ–∑  24 —á–∞—Å–∞. 

  –ü–æ—Ä–∞ –ø—Ä–∏–Ω–∏–º–∞—Ç—å —Ä–µ—à–µ–Ω–∏–µ.