mail1310: |
  –ü—Ä–∏–≤–µ—Ç, –ø—Ä–æ–¥–∞–∂–∞ –º–æ–µ–≥–æ –ê–≤—Ç–æ—Ä—Å–∫–æ–≥–æ –∫—É—Ä—Å–∞ ¬´–ü—Ä–æ –±–µ—Ä–µ–º–µ–Ω–Ω–æ—Å—Ç—å¬ª –û–¢–ö–†–´–¢–ê‚úÖ 

  –í –Ω–µ–º —è —Ä–∞—Å—Å–∫–∞–∑–∞–ª–∞ –∫–∞–∫ –ó–∞—á–∞—Ç—å, –í—ã–Ω–æ—Å–∏—Ç—å –∏ –†–æ–¥–∏—Ç—å –ó–¥–æ—Ä–æ–≤—É—é –∏ –£–º–Ω–µ–Ω—å–∫—É—é –õ—è–ª–µ—á–∫—É‚ù§Ô∏è

  –ë–æ–ª–µ–µ 10 —á–∞—Å–æ–≤ –¥–æ–∫–∞–∑–∞—Ç–µ–ª—å–Ω–æ–π –º–µ–¥–∏—Ü–∏–Ω—ã –ø–æ —Å–∞–º—ã–º –ø–æ—Å–ª–µ–¥–Ω–∏–º –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏—è–º –≤ –æ–±–ª–∞—Å—Ç–∏ –∑–∞—á–∞—Ç–∏—è –∏ –±–µ—Ä–µ–º–µ–Ω–Ω–æ—Å—Ç–∏üíï