links:
  main: "https://t.me/dr_rafikova_bot"
  offer: "https://disk.yandex.ru/i/nmeZyP3EN503bw"
  privacy: "https://disk.yandex.ru/i/cl2qLv-Rp4V36g"
  consent: "https://disk.yandex.ru/i/5r2kBM9WqRx4jQ"
  chargeback: "https://telegra.ph/Zayavlenie-na-vozvrat-04-03"
person_info: |
  ИП Рафикова Руфия Ханяфиевна
  ОГРНИП 324169000212590 
  ИНН 164408725851 
  E-mail: aliyaildusovna1@icloud.com  
