links:
  main: "https://t.me/dr_rafikova_bot"
  offer: "https://disk.yandex.ru/i/2X61e-I-RdvOGA"
  privacy: "https://disk.yandex.ru/i/iy5PL6yziZVMFQ"
  consent: "https://disk.yandex.ru/i/5l5qGq9Tk-15PA"
  personal: "https://disk.yandex.ru/i/K4V9HYzcqot4Sg"
  chargeback: "https://telegra.ph/Zayavlenie-na-vozvrat-04-03"
person_info: |
  ИП Рафикова Руфия Ханяфиевна
  ОГРНИП 324169000212590 
  ИНН 164408725851 
  E-mail: aliyaildusovna1@icloud.com  
